default:
    just --list

fmt:
    ruff format .

lint:
    ruff check .

lint-fix:
    ruff check --fix .

typecheck:
    pyright

test:
    uv run python -m unittest discover

run file="main.py":
    uv run python {{file}}
